name = "web-mcp"
main = "source/worker.ts"
compatibility_date = "2025-01-01"

[assets]
directory = "./build/output"
binding = "ASSETS"
run_worker_first = true

[[routes]]
pattern = "browser-mcp.com"
custom_domain = true
